<?php
return [
    'en' => [
        'home' => 'Home', 'schedule' => 'Schedule', 'contacts' => 'Contacts',
        'login' => 'Login', 'register' => 'Register', 'logout' => 'Logout',
        'profile' => 'Profile', 'admin_panel' => 'Admin Panel',
        'welcome' => 'Welcome', 'name' => 'Name', 'email' => 'Email',
        'phone' => 'Phone', 'address' => 'Address', 'password' => 'Password',
        'confirm_pass' => 'Confirm Password', 'current_pass' => 'Current Password',
        'new_pass' => 'New Password', 'update_info' => 'Update Info',
        'update_pass' => 'Update Password', 'class_details' => 'Class Details',
        'participants' => 'Participants', 'hero_h1' => 'Train Like an Athlete.',
        'hero_p' => 'Premium fitness experience with elite trainers and science-based programs.',
        'join_now' => 'Join Now', 'view_plans' => 'View Plans',
        'select_class' => 'Select a class on the calendar to view full details here.',
        'join_msg' => 'Join a class to see who else is coming!',
        'why_choose_us' => 'Why Choose Us', 'elite_equip' => 'Elite Equipment',
        'expert_coaches' => 'Expert Coaches', 'flex_training' => 'Flexible Training',
        'our_trainers' => 'Our Trainers', 'pop_classes' => 'Popular Classes',
        'member_plans' => 'Membership Plans', 'start_trans' => 'Start Your Transformation Today',
        'get_started' => 'Get Started', 'name_label' => 'Name', 'email_label' => 'Email Address',
        'phone_label' => 'Phone Number', 'address_label' => 'Address',
        'time' => 'Time', 'attendance' => 'Attendance', 'class_full' => 'Class Full',
        'loading_athletes' => 'Loading athletes...', 'no_participants' => 'No one has joined yet. Be the first!',
        'total_joined' => 'Total joined', 'cancel_my_res' => 'Cancel My Reservation',
        'export_excel' => 'Export Participants (Excel)', 'print_pdf' => 'Print Participant List (PDF)',
        'create_workout' => 'Create Workout', 'save' => 'Save', 'delete' => 'Delete', 'close' => 'Close',
        'forgot_password' => 'Forgot Password?',
        'cancel' => 'Cancel', 'login_to_view' => 'Please login to view participants.', 'no_account' => 'No account?', 'already_account' => 'Already have an account?',
        'gym_only' => 'Gym access only', 'gym_classes' => 'Gym + Classes', 'trainer_included' => 'Gym + Classes and Personal trainer included',
        'join' => 'Join', 'basic' => 'Basic', 'advanced' => 'Advanced', 'pro' => 'Pro',
        'acc_details' => 'Account Details', 'change_pass' => 'Change Password',
        'pass_hint' => '6+ chars, 1 uppercase, 1 number, 1 symbol',
        'membership_status' => 'Membership Status',
        'no_active_membership' => 'No Active Membership',
        'expires_on' => 'Expires on:',
        'days_left' => 'days left', 'boxing' => 'Boxing', 'yoga' => 'Yoga', 'crossfit' => 'CrossFit',
        'none' => 'None',
        'strength_coach' => 'Strength Coach', 'yoga_inst' => 'Yoga Instructor', 'cf_coach' => 'CrossFit Coach',
        'res_cancelled' => 'Reservation cancelled. Select again to refresh.',
        'confirm_cancel' => 'Are you sure you want to cancel your reservation?',
        'today' => 'Today',
        'remaining' => 'Remaining',
        'reserve' => 'Reserve',
        'assign_membership' => 'Assign Membership',
        'select_user' => 'Select User',
        'confirm_delete' => 'Delete class?',
        'save_failed' => 'Save failed',
        'sidebar_hint' => 'Click the event again to open the reservation or edit modal.',
        'elite_p' => 'World-class machines designed for performance and safety.', // Corrected typo from previous context
        'expert_p' => 'Certified professionals guiding your transformation.', // Corrected typo from previous context
        'flex_p' => 'Boxing, yoga, crossfit and personal coaching programs.', // Corrected typo from previous context
        'cta_members' => '500+ Members',
        'cta_booking' => 'Live Booking',
        'cta_results' => 'Pro Results',
        'privacy_policy' => 'Privacy Policy',
        'facebook' => 'Facebook',
        'instagram' => 'Instagram',
        'twitter' => 'X (Twitter)',
        'cookie_msg' => 'We use cookies to improve your experience and collect site usage statistics.',
        'cookie_deny' => 'Deny',
        'cookie_accept' => 'Accept',
        'privacy_title' => 'Privacy Policy',
        'privacy_intro' => 'This Privacy Policy describes how MyGoToGym collects, uses, and discloses your Personal Information when you visit or make a purchase from the Site.',
        'p_sec1_t' => '1. Information We Collect',
        'p_sec1_c' => 'We collect personal information you provide directly to us, such as your name, email address, phone number, and membership details when you register or use our services.',
        'p_sec2_t' => '2. How We Use Your Information',
        'p_sec2_c' => 'We use the information we collect to provide, maintain, and improve our services, process transactions, send you notifications, and for marketing purposes.',
        'p_sec3_t' => '3. Sharing Your Personal Information',
        'p_sec3_c' => 'We do not share your personal information with third parties except as necessary to provide our services, comply with the law, or protect our rights.',
        'p_sec4_t' => '4. Your Rights',
        'p_sec4_c' => 'You have the right to access, correct, or delete your personal information. Please contact us to exercise these rights.',
        'p_sec5_t' => '5. Changes to This Policy',
        'p_sec5_c' => 'We may update this privacy policy from time to time. We will notify you of any changes by posting the new policy on this page.',
        'p_contact' => 'If you have any questions about this Privacy Policy, please contact us at info@mygotogym.com.',
        'confirm_membership' => 'Confirm Membership',
        'confirm_purchase' => 'Confirm Purchase',
        'membership_terms' => 'By confirming, you agree to our membership terms and conditions.',
        'payment_history' => 'Payment History',
        'impressum_title' => 'Impressum',
        'impressum_operator' => 'Legal Operator',
        'impressum_contact' => 'Contact Information',
        'impressum_disclaimer' => 'Disclaimer',
        'impressum_disclaimer_text' => 'The content of our pages was created with great care. However, we cannot guarantee the accuracy, completeness, or timeliness of the content.',
        'date' => 'Date',
        'amount' => 'Amount',
        'status' => 'Status',
        'no_payments' => 'No payment history found.',
        'holiday_error' => 'Workouts cannot be scheduled on public holidays.',
        'trainer_label' => 'Trainer',
        'admin_name' => 'MyGoToGym Administration',
        'verified_status' => 'Verified',
        'verified_message' => 'Email successfully verified! You can now login.',
        'go_to_login' => 'Go to Login',
        'invalid_link_status' => 'Invalid Link',
        'invalid_link_message_generic' => 'Invalid verification link.',
        'invalid_or_expired_token' => 'Invalid or expired verification token.',
        'try_registering_again' => 'Try Registering Again',
        'back_to_home' => 'Back to Home',
        'resend_verification' => 'Resend Verification Email',
        'reset_link_sent' => 'If that email is registered and verified, a reset link has been sent.',
        'pass_reset_subject' => 'Reset your MyGoToGym Password',
        'pass_reset_welcome' => 'Password Reset',
        'pass_reset_body' => 'You requested a password reset. Click the button below to set a new password. This link expires in 1 hour.',
        'pass_reset_button' => 'Reset Password',
        'pass_reset_footer' => 'If you did not request this, please ignore this email.',
        'password_mismatch' => 'Passwords do not match.',
        'password_min_length' => 'Password must be at least 8 characters.',
        'password_updated_success' => 'Password updated successfully!',
        'token_invalid' => 'Token invalid or expired.',
        'enter_email_to_reset' => 'Enter your email to receive a reset link.',
        'reset_cooldown' => 'Please wait 5 minutes before requesting another reset link.',
        'send_reset_link' => 'Send Reset Link'
    ],
    'lv' => [
        'home' => 'Sākums', 'schedule' => 'Grafiks', 'contacts' => 'Kontakti',
        'login' => 'Ienākt', 'register' => 'Reģistrēties', 'logout' => 'Iziet',
        'profile' => 'Profils', 'admin_panel' => 'Admin Panelis',
        'welcome' => 'Sveicināti', 'name' => 'Vārds', 'email' => 'E-pasts',
        'phone' => 'Telefons', 'address' => 'Adrese', 'password' => 'Parole',
        'confirm_pass' => 'Apstiprināt paroli', 'current_pass' => 'Pašreizējā parole',
        'new_pass' => 'Jaunā parole', 'update_info' => 'Atjaunot info',
        'update_pass' => 'Mainīt paroli', 'class_details' => 'Nodarbības detaļas',
        'participants' => 'Dalībnieki', 'hero_h1' => 'Trenējies kā atlēts.',
        'hero_p' => 'Premium fitnesa pieredze ar elites treneriem un zinātnē balstītām programmām.',
        'join_now' => 'Pievienoties', 'view_plans' => 'Plāni',
        'select_class' => 'Izvēlieties nodarbību kalendārā, lai redzētu detaļas šeit.',
        'join_msg' => 'Pievienojies nodarbībai, lai redzētu, kas vēl nāks!',
        'why_choose_us' => 'Kāpēc izvēlēties mūs', 'elite_equip' => 'Elites aprīkojums',
        'expert_coaches' => 'Ekspertu treneri', 'flex_training' => 'Fleksibli treniņi',
        'our_trainers' => 'Mūsu treneri', 'pop_classes' => 'Populāras nodarbības',
        'member_plans' => 'Abonementu plāni', 'start_trans' => 'Sāc savas pārmaiņas šodien',
        'get_started' => 'Sākt tūlīt', 'name_label' => 'Vārds', 'email_label' => 'E-pasta adrese',
        'phone_label' => 'Telefona numurs', 'address_label' => 'Adrese',
        'time' => 'Laiks', 'attendance' => 'Apmeklējums', 'class_full' => 'Grupa pilna',
        'loading_athletes' => 'Ielādē atlētus...', 'no_participants' => 'Neviens vēl nav pieteicies. Esi pirmais!',
        'total_joined' => 'Kopā pieteikušies', 'cancel_my_res' => 'Atcelt manu rezervāciju',
        'export_excel' => 'Eksportēt dalībniekus (Excel)', 'print_pdf' => 'Drukāt sarakstu (PDF)',
        'create_workout' => 'Izveidot treniņu', 'save' => 'Saglabāt', 'delete' => 'Dzēst', 'close' => 'Aizvērt',
        'forgot_password' => 'Aizmirsu paroli?',
        'cancel' => 'Atcelt', 'login_to_view' => 'Lūdzu, ienāciet, lai redzētu dalībniekus.', 'no_account' => 'Nav konta?', 'already_account' => 'Jau ir konts?',
        'gym_only' => 'Tikai trenažieru zāle', 'gym_classes' => 'Zāle + Nodarbības', 'trainer_included' => 'Zāle + Nodarbības un personīgais treneris',
        'join' => 'Pievienoties', 'basic' => 'Pamata', 'advanced' => 'Paplašinātais', 'pro' => 'Pro',
        'acc_details' => 'Konta informācija', 'change_pass' => 'Mainīt paroli',
        'pass_hint' => '6+ zīmes, 1 lielais burts, 1 skaitlis, 1 simbols',
        'membership_status' => 'Abonementa statuss',
        'no_active_membership' => 'Nav aktīva abonementa',
        'expires_on' => 'Derīgs līdz:',
        'days_left' => 'dienas atlikušas', 'boxing' => 'Bokss', 'yoga' => 'Joga', 'crossfit' => 'Krossfits',
        'none' => 'Nav',
        'strength_coach' => 'Spēka treneris', 'yoga_inst' => 'Jogas instruktore', 'cf_coach' => 'Krossfita treneris',
        'res_cancelled' => 'Rezervācija atcelta. Izvēlieties vēlreiz, lai atjauninātu.',
        'confirm_cancel' => 'Vai tiešām vēlaties atcelt rezervāciju?',
        'today' => 'Šodien',
        'remaining' => 'Atlicis',
        'reserve' => 'Rezervēt',
        'assign_membership' => 'Piešķirt abonementu',
        'select_user' => 'Izvēlēties lietotāju',
        'confirm_delete' => 'Dzēst nodarbību?',
        'save_failed' => 'Saglabāšana neizdevās',
        'sidebar_hint' => 'Noklikšķiniet vēlreiz, lai atvērtu rezervācijas vai rediģēšanas logu.',
        'elite_p' => 'Pasaules līmeņa trenažieri veiktspējai un drošībai.', // Corrected typo from previous context
        'expert_p' => 'Sertificēti profesionāļi jūsu izaugsmei.', // Corrected typo from previous context
        'flex_p' => 'Boksa, jogas, krossfita un personīgo treniņu programmas.', // Corrected typo from previous context
        'cta_members' => '500+ Dalībnieki',
        'cta_booking' => 'Tiešsaistes rezervācija',
        'cta_results' => 'Profesionāli rezultāti',
        'privacy_policy' => 'Privātuma politika',
        'facebook' => 'Facebook',
        'instagram' => 'Instagram',
        'twitter' => 'X (Twitter)',
        'cookie_msg' => 'Mēs izmantojam sīkdatnes, lai uzlabotu jūsu pieredzi un apkopotu vietnes lietošanas statistiku.',
        'cookie_deny' => 'Noraidīt',
        'cookie_accept' => 'Pieņemt',
        'privacy_title' => 'Privātuma Politika',
        'privacy_intro' => 'Šī Privātuma Politika apraksta, kā MyGoToGym vāc, izmanto un atklāj jūsu Personisko Informāciju, kad apmeklējat vai veicat pirkumu vietnē.',
        'p_sec1_t' => '1. Mūsu vāktā informācija',
        'p_sec1_c' => 'Mēs apkopojam personisko informāciju, ko jūs mums sniedzat tieši, piemēram, jūsu vārdu, e-pasta adresi, tālruņa numuru un dalības informāciju, kad reģistrējaties vai izmantojat mūsu pakalpojumus.',
        'p_sec2_t' => '2. Kā mēs izmantojam jūsu informāciju',
        'p_sec2_c' => 'Mēs izmantojam apkopoto informāciju, lai nodrošinātu, uzturētu un uzlabotu mūsu pakalpojumus, apstrādātu darījumus, sūtītu jums paziņojumus un mārketinga nolūkos.',
        'p_sec3_t' => '3. Personiskās informācijas koplietošana',
        'p_sec3_c' => 'Mēs nekopīgojam jūsu personisko informāciju ar trešajām personām, izņemot gadījumus, kad tas ir nepieciešams mūsu pakalpojumu sniegšanai, likumu ievērošanai vai mūsu tiesību aizsardzībai.',
        'p_sec4_t' => '4. Jūsu tiesības',
        'p_sec4_c' => 'Jums ir tiesības piekļūt, labot vai dzēst savu personisko informāciju. Lūdzu, sazinieties ar mums, lai izmantotu šīs tiesības.',
        'p_sec5_t' => '5. Izmaiņas šajā politikā',
        'p_sec5_c' => 'Mēs laiku pa laikam varam atjaunināt šo privātuma politiku. Mēs jūs informēsim par jebkurām izmaiņām, publicējot jauno politiku šajā lapā.',
        'p_contact' => 'Ja jums ir kādi jautājumi par šo Privātuma Politiku, lūdzu, sazinieties ar mums pa e-pastu info@mygotogym.com.',
        'confirm_membership' => 'Apstiprināt dalību',
        'confirm_purchase' => 'Apstiprināt pirkumu',
        'membership_terms' => 'Apstiprinot, jūs piekrītat mūsu dalības noteikumiem un nosacījumiem.',
        'payment_history' => 'Maksājumu vēsture',
        'impressum_title' => 'Impresums',
        'impressum_operator' => 'Juridiskais operators',
        'impressum_contact' => 'Kontaktinformācija',
        'impressum_disclaimer' => 'Atruna',
        'impressum_disclaimer_text' => 'Mūsu lapu saturs ir izveidots ar lielu rūpību. Tomēr mēs nevaram garantēt satura pareizību, pilnīgumu vai savlaicīgumu.',
        'date' => 'Datums',
        'amount' => 'Summa',
        'status' => 'Statuss',
        'no_payments' => 'Maksājumu vēsture nav atrasta.',
        'holiday_error' => 'Nodarbības nevar plānot svētku dienās.',
        'trainer_label' => 'Treneris',
        'admin_name' => 'MyGoToGym administrācija',
        'verified_status' => 'Apstiprināts',
        'verified_message' => 'E-pasts veiksmīgi apstiprināts! Tagad varat pieteikties.',
        'go_to_login' => 'Doties uz pieteikšanos',
        'invalid_link_status' => 'Nederīga saite',
        'invalid_link_message_generic' => 'Nederīga verifikācijas saite.',
        'invalid_or_expired_token' => 'Nederīga vai beidzies verifikācijas žetons.',
        'try_registering_again' => 'Mēģiniet reģistrēties vēlreiz',
        'back_to_home' => 'Atpakaļ uz sākumu',
        'resend_verification' => 'Nosūtīt verifikācijas e-pastu vēlreiz',
        'reset_link_sent' => 'Ja šis e-pasts ir reģistrēts un apstiprināts, atiestatīšanas saite ir nosūtīta.',
        'pass_reset_subject' => 'Atiestatiet savu MyGoToGym paroli',
        'pass_reset_welcome' => 'Paroles atiestatīšana',
        'pass_reset_body' => 'Jūs pieprasījāt paroles atiestatīšanu. Noklikšķiniet uz zemāk esošās pogas, lai iestatītu jaunu paroli. Šī saite ir derīga 1 stundu.',
        'pass_reset_button' => 'Atiestatīt paroli',
        'pass_reset_footer' => 'Ja jūs to nepieprasījāt, lūdzu, ignorējiet šo e-pastu.',
        'password_mismatch' => 'Paroles nesakrīt.',
        'password_min_length' => 'Parolei jābūt vismaz 8 rakstzīmēm.',
        'password_updated_success' => 'Parole veiksmīgi atjaunota!',
        'token_invalid' => 'Žetons ir nederīgs vai beidzies.',
        'enter_email_to_reset' => 'Ievadiet savu e-pastu, lai saņemtu atiestatīšanas saiti.',
        'reset_cooldown' => 'Lūdzu, uzgaidiet 5 minūtes pirms pieprasāt jaunu saiti.',
        'send_reset_link' => 'Sūtīt atiestatīšanas saiti'
    ],
    'ru' => [
        'home' => 'Главная', 'schedule' => 'Расписание', 'contacts' => 'Контакты',
        'login' => 'Войти', 'register' => 'Регистрация', 'logout' => 'Выход',
        'profile' => 'Профиль', 'admin_panel' => 'Админ Панель',
        'welcome' => 'Добро пожаловать', 'name' => 'Имя', 'email' => 'Эл. почта',
        'phone' => 'Телефон', 'address' => 'Адрес', 'password' => 'Пароль',
        'confirm_pass' => 'Подтвердите пароль', 'current_pass' => 'Текущий пароль',
        'new_pass' => 'Новый пароль', 'update_info' => 'Обновить инфо',
        'update_pass' => 'Сменить пароль', 'class_details' => 'Детали занятия',
        'participants' => 'Участники', 'hero_h1' => 'Тренируйся как атлет.',
        'hero_p' => 'Премиальный фитнес с элитными тренерами и научными программами.',
        'join_now' => 'Записаться', 'view_plans' => 'Планы',
        'select_class' => 'Выберите занятие в календаре для деталей здесь.',
        'join_msg' => 'Присоединяйтесь, чтобы увидеть список участников!',
        'why_choose_us' => 'Почему мы', 'elite_equip' => 'Элитное оборудование',
        'expert_coaches' => 'Экспертные тренеры', 'flex_training' => 'Гибкие тренировки',
        'our_trainers' => 'Наши тренеры', 'pop_classes' => 'Популярные занятия',
        'member_plans' => 'Планы подписки', 'start_trans' => 'Начни трансформацию сегодня',
        'get_started' => 'Начать', 'name_label' => 'Имя', 'email_label' => 'Эл. почта',
        'phone_label' => 'Номер телефона', 'address_label' => 'Адрес',
        'time' => 'Время', 'attendance' => 'Посещаемость', 'class_full' => 'Группа полна',
        'loading_athletes' => 'Загрузка атлетов...', 'no_participants' => 'Никто еще не записался. Будь первым!',
        'total_joined' => 'Всего участников', 'cancel_my_res' => 'Отменить мою запись',
        'export_excel' => 'Экспорт участников (Excel)', 'print_pdf' => 'Печать списка (PDF)',
        'create_workout' => 'Создать тренировку', 'save' => 'Сохранить', 'delete' => 'Удалить', 'close' => 'Закрыть',
        'forgot_password' => 'Забыли пароль?',
        'cancel' => 'Отмена', 'login_to_view' => 'Пожалуйста, войдите, чтобы увидеть участников.', 'no_account' => 'Нет аккаунта?', 'already_account' => 'Уже есть аккаунт?',
        'gym_only' => 'Только тренажерный зал', 'gym_classes' => 'Зал + Занятия', 'trainer_included' => 'Зал + Занятия и персональный тренер включен',
        'join' => 'Вступить', 'basic' => 'Базовый', 'advanced' => 'Продвинутый', 'pro' => 'Про',
        'acc_details' => 'Данные аккаунта', 'change_pass' => 'Сменить пароль',
        'pass_hint' => '6+ симв., 1 заглавная, 1 цифра, 1 символ',
        'membership_status' => 'Статус подписки',
        'no_active_membership' => 'Нет активной подписки',
        'expires_on' => 'Истекает:',
        'days_left' => 'дней осталось', 'boxing' => 'Бокс', 'yoga' => 'Йога', 'crossfit' => 'Кроссфит',
        'none' => 'Нет',
        'strength_coach' => 'Тренер по силе', 'yoga_inst' => 'Инструктор по йоге', 'cf_coach' => 'Тренер по кроссфиту',
        'res_cancelled' => 'Запись отменена. Выберите снова для обновления.',
        'confirm_cancel' => 'Вы уверены, что хотите отменить запись?',
        'today' => 'Сегодня',
        'remaining' => 'Осталось',
        'reserve' => 'Забронировать',
        'assign_membership' => 'Назначить подписку',
        'select_user' => 'Выбрать пользователя',
        'confirm_delete' => 'Удалить занятие?',
        'save_failed' => 'Ошибка сохранения',
        'sidebar_hint' => 'Нажмите на событие еще раз, чтобы открыть окно бронирования или редактирования.',
        'elite_p' => 'Тренажеры мирового класса для производительности и безопасности.', // Corrected typo from previous context
        'expert_p' => 'Сертифицированные профи для вашего прогресса.', // Corrected typo from previous context
        'flex_p' => 'Программы бокса, йоги, кроссфита и личного коучинга.', // Corrected typo from previous context
        'cta_members' => '500+ Участников',
        'cta_booking' => 'Онлайн бронирование',
        'cta_results' => 'Профессиональные результаты',
        'privacy_policy' => 'Политика конфиденциальности',
        'facebook' => 'Facebook',
        'instagram' => 'Instagram',
        'twitter' => 'X (Twitter)',
        'cookie_msg' => 'Мы используем файлы cookie для улучшения вашего взаимодействия с сайтом и сбора статистики использования.',
        'cookie_deny' => 'Отклонить',
        'cookie_accept' => 'Принять',
        'privacy_title' => 'Политика конфиденциальности',
        'privacy_intro' => 'Настоящая Политика конфиденциальности описывает, как MyGoToGym собирает, использует и раскрывает вашу Личную информацию, когда вы посещаете или совершаете покупку на Сайте.',
        'p_sec1_t' => '1. Собираемая нами информация',
        'p_sec1_c' => 'Мы собираем личную информацию, которую вы предоставляете нам напрямую, такую как ваше имя, адрес электронной почты, номер телефона и данные о членстве, когда вы регистрируетесь или используете наши услуги.',
        'p_sec2_t' => '2. Как мы используем вашу информацию',
        'p_sec2_c' => 'Мы используем собранную информацию для предоставления, поддержки и улучшения наших услуг, обработки транзакций, отправки вам уведомлений и в маркетинговых целях.',
        'p_sec3_t' => '3. Передача вашей личной информации',
        'p_sec3_c' => 'Мы не передаем вашу личную информацию третьим лицам, за исключением случаев, когда это необходимо для предоставления наших услуг, соблюдения законодательства или защиты наших прав.',
        'p_sec4_t' => '4. Ваши права',
        'p_sec4_c' => 'Вы имеете право на доступ, исправление или удаление вашей личной информации. Пожалуйста, свяжитесь с нами, чтобы воспользоваться этими правами.',
        'p_sec5_t' => '5. Изменения в этой политике',
        'p_sec5_c' => 'Мы можем время от времени обновлять настоящую политику конфиденциальности. Мы уведомим вас о любых изменениях, разместив новую политику на этой странице.',
        'p_contact' => 'Если у вас есть какие-либо вопросы относительно настоящей Политики конфиденциальности, пожалуйста, свяжитесь с нами по адресу info@mygotogym.com.',
        'confirm_membership' => 'Подтвердить членство',
        'confirm_purchase' => 'Подтвердить покупку',
        'membership_terms' => 'Подтверждая, вы соглашаетесь с нашими условиями членства.',
        'payment_history' => 'История платежей',
        'impressum_title' => 'Выходные данные',
        'impressum_operator' => 'Юридический оператор',
        'impressum_contact' => 'Контактная информация',
        'impressum_disclaimer' => 'Отказ от ответственности',
        'impressum_disclaimer_text' => 'Содержимое наших страниц было создано с большой тщательностью. Однако мы не можем гарантировать точность, полноту или своевременность контента.',
        'date' => 'Дата',
        'amount' => 'Сумма',
        'status' => 'Статус',
        'no_payments' => 'История платежей не найдена.',
        'holiday_error' => 'Тренировки нельзя планировать в праздничные дни.',
        'trainer_label' => 'Тренер',
        'admin_name' => 'Администрация MyGoToGym',
        'verified_status' => 'Подтверждено',
        'verified_message' => 'Электронная почта успешно подтверждена! Теперь вы можете войти.',
        'go_to_login' => 'Перейти к входу',
        'invalid_link_status' => 'Неверная ссылка',
        'invalid_link_message_generic' => 'Неверная ссылка для подтверждения.',
        'invalid_or_expired_token' => 'Неверный или просроченный токен подтверждения.',
        'try_registering_again' => 'Попробуйте зарегистрироваться снова',
        'back_to_home' => 'Вернуться на главную',
        'resend_verification' => 'Отправить письмо с подтверждением еще раз',
        'reset_link_sent' => 'Если этот адрес зарегистрирован и подтвержден, ссылка для сброса отправлена.',
        'pass_reset_subject' => 'Сброс пароля вашего аккаунта MyGoToGym',
        'pass_reset_welcome' => 'Сброс пароля',
        'pass_reset_body' => 'Вы запросили сброс пароля. Нажмите кнопку ниже, чтобы установить новый пароль. Ссылка действительна в течение 1 часа.',
        'pass_reset_button' => 'Сбросить пароль',
        'pass_reset_footer' => 'Если вы не запрашивали это, просто проигнорируйте письмо.',
        'password_mismatch' => 'Пароли не совпадают.',
        'password_min_length' => 'Пароль должен содержать не менее 8 символов.',
        'password_updated_success' => 'Пароль успешно обновлен!',
        'token_invalid' => 'Токен недействителен или просрочен.',
        'enter_email_to_reset' => 'Введите свой e-mail, чтобы получить ссылку для сброса.',
        'reset_cooldown' => 'Пожалуйста, подождите 5 минут перед повторным запросом.',
        'send_reset_link' => 'Отправить ссылку для сброса'
    ]
];